- name: Create Loopback0 interfaces
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "Loopback0"
      device: "Leaf-{{ item }}"
      description: "BGP EVPN Peering"
      form_factor: Virtual
    state: present
  loop: "{{ leaf_ids }}"

- name: Create Loopback1 interfaces
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "Loopback1"
      device: "Leaf-{{ item }}"
      description: "VXLAN VTEP"
      form_factor: Virtual
    state: present
  loop: "{{ leaf_ids }}"

- name: Create ip and attach to interface Loopback0
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ loopback0_network | ipmath(item) }}"
      tenant: Arista EVPN Lab
      vrf: arista-evpn-lab
      description: "Leaf-{{ item }} Loopback0"
      role: Loopback
      assigned_object:
        name: "Loopback0"
        device: "Leaf-{{ item }}"
    state: present
  loop: "{{ leaf_ids }}"


- name: Create ip and attach to interface Loopback1
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ loopback1_network | ipmath(vtep_number) }}"
      tenant: Arista EVPN Lab
      vrf: arista-evpn-lab
      description: "VTEP-{{ vtep_number }} Loopback1"
      role: Anycast
      assigned_object:
        name: "Loopback1"
        device: "Leaf-{{ item }}"
    state: present
  loop: "{{ leaf_ids }}"