- name: Create MGMT ip and attach to interface
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ leaf_mgmt_subnet | ipmath(item) }}/{{ leaf_mgmt_mask }}"
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      description: "Leaf-{{ item }} mgmt"
      assigned_object:
        name: "Management1"
        device: "Leaf-{{ item }}"
    state: present
  loop: "{{ leaf_ids }}"


- name: Assign MGMT IP as Primary for device
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "Leaf-{{ item }}"
      tenant: Arista EVPN Lab
      primary_ip4: "{{ leaf_mgmt_subnet | ipmath(item) }}"
    state: present
  loop: "{{ leaf_ids }}"