- name: Create VLAN Interfaces
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.0.name }}"
      device: "Leaf-{{ item.1 }}"
      description: "{{ item.0.description }}"
      form_factor: Virtual
    state: present
  loop: "{{ vlan_intf | product(leaf_ids) |list }}"


- name: Create IP and attach to interface Vlan4093
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ mlag_ibgp_subnet | ipaddr(index) }}"
      tenant: Arista EVPN Lab
      vrf: arista-evpn-lab
      description: "Leaf-{{ item }} MLAG iBGP"
      role: Anycast
      assigned_object:
        name: "Vlan4093"
        device: "Leaf-{{ item }}"
    state: present
  loop: "{{ leaf_ids }}"
  loop_control:
    index_var: index


- name: Create IP and attach to interface Vlan4094
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ mlag_peer_link_subnet | ipaddr(index) }}"
      tenant: Arista EVPN Lab
      vrf: arista-evpn-lab
      description: "Leaf-{{ item }} MLAG Peer-Link"
      role: Anycast
      assigned_object:
        name: "Vlan4094"
        device: "Leaf-{{ item }}"
    state: present
  loop: "{{ leaf_ids }}"
  loop_control:
    index_var: index